# Generated by Django 2.1.7 on 2019-04-28 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('bauthor', models.CharField(blank=True, max_length=20, null=True, verbose_name='作者')),
                ('bpages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('bpubtime', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('breadtimes', models.IntegerField(blank=True, null=True, verbose_name='阅读次数')),
                ('bisbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='isbn号')),
                ('bavescore', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='平均分')),
                ('bcontent', models.TextField(blank=True, null=True, verbose_name='内容概要')),
                ('bimageurl', models.CharField(blank=True, max_length=100, null=True)),
                ('bsystime', models.DateField(auto_now_add=True, verbose_name='系统添加时间')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-id'],
            },
            managers=[
                ('bookObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rreview', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('rusername', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('ruserphoto', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户头像')),
                ('rpublishtime', models.DateField(auto_now_add=True, null=True, verbose_name='发表时间')),
                ('rbookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Books', verbose_name='图书id')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-rpublishtime'],
            },
            managers=[
                ('reviewObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stag', models.BooleanField(default=True)),
                ('sbookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Books', verbose_name='图书id')),
            ],
            options={
                'db_table': 'score',
                'ordering': ['-id'],
            },
            managers=[
                ('scoreObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uopenid', models.CharField(default='defaultopenid', max_length=30, primary_key=True, serialize=False, verbose_name='用户openid')),
                ('uname', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('ugender', models.BooleanField(default=False)),
                ('uphoto', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户头像')),
                ('ulocation', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地区')),
                ('uentrytime', models.DateTimeField(auto_now=True, verbose_name='最近登陆时间')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-uentrytime'],
            },
            managers=[
                ('userObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='suserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Users', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='ruserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Users', verbose_name='用户id'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('suserid', 'sbookid')},
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('ruserid', 'rbookid')},
        ),
    ]
